on:
  push:
    paths-ignore:
      - 'README.md'

jobs:
  cd_deploy:
    name: Deploy Azure Environment
    environment: prod
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2

      - name: Azure CLI Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          enable-AzPSSession: true

      - id: resolve-shared-resources
        name: Resolve shared resources
        working-directory: .\deployment
        run: |
          .\ResolveSharedResources.ps1

      - name: Deploy shared services
        id: deploysharedservices
        uses: azure/arm-deploy@v1
        with:
          deploymentName: 'shared-services-${{ github.run_number }}'
          resourceGroupName: ${{ steps.resolve-shared-resources.outputs.appResourceGroup }}
          template: ./deployment/shared-services.bicep
          parameters: >
            prefix=${{ secrets.PREFIX }}

      - name: Deploy personal
        id: deploypersonal
        uses: azure/arm-deploy@v1
        with:
          deploymentName: 'personal-${{ github.run_number }}'
          resourceGroupName: ${{ steps.resolve-shared-resources.outputs.personalResourceGroup }}
          template: ./deployment/personal.bicep
          parameters: >
            prefix=${{ secrets.PREFIX }}
